src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Vous devez saisir un titre.')]
    private string $title;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'Vous devez saisir du contenu.')]
    private string $content;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $isDone;

    #[ORM\Column()]
    private ?DateTimeImmutable $created_at;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    private ?Users $User = null;

    public function __construct()
    {
        $this->isDone = false;
    }

    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    #[ORM\PrePersist]
    public function setCreatedAt(): void
    {
        $this->created_at = new DateTimeImmutable();
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function isDone(): bool
    {
        return $this->isDone;
    }

    public function toggle(bool $flag): void
    {
        $this->isDone = $flag;
    }

    public function getUser(): ?Users
    {
        return $this->User;
    }

    public function setUser(?Users $User): static
    {
        $this->User = $User;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>To Do List app</title>

    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}

</head>

<body>
<nav class="navbar navbar-light navbar-fixed-top" style="background-color: #e3f2fd;" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">To Do List app</a>

            <img src="{{ asset('img/Logo_OpenClassrooms.png') }}" alt="OpenClassrooms" />
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <a href="{{ path('user_create') }}" class="btn btn-primary">Créer un utilisateur</a>

        {% if app.user %}
            <a href="{{ path('app_logout') }}" class="pull-right btn btn-danger">Se déconnecter</a>
        {% endif %}

        {% if not app.user and 'login' != app.request.attributes.get('_route') %}
            <a href="{{ path('app_login') }}" class="btn btn-success">Se connecter</a>
        {% endif %}
    </div>

    <div class="row">
        <div class="col-md-12">
            {% for flash_message in app.session.flashBag.get('success') %}
                <div class="alert alert-success" role="alert">
                    <strong>Superbe !</strong> {{ flash_message }}
                </div>
            {% endfor %}

            {% for flash_message in app.session.flashBag.get('error') %}
                <div class="alert alert-danger" role="alert">
                    <strong>Oops !</strong> {{ flash_message }}
                </div>
            {% endfor %}

            {% block header_title %}{% endblock %}
            {% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_homepage.jpg') }}" alt="todo list">{% endblock %}
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
<!-- /.container -->

<div class="container">

    <hr>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p class="pull-right">Copyright &copy; OpenClassrooms</p>
            </div>
        </div>
    </footer>

</div>

</body>
</html>